### ISSUE TITLE
Global style for svg in librari

### ISSUE THREAD

**Issue by saschati** [kavindu-mane/react-percentage-bar#2]
Hello, I came across this great library and realized that it would suit my needs, but I came across the following moment:
1. Global styles for svg, it's not very good because all svg on the site suffer, can't make them relative?
![image](https://github.com/kavindu-mane/react-percentage-bar/assets/36109878/0761e9d2-3b17-477f-b98b-9b7725641d95)
2. Would it be possible to modify the library to use gradients in the progress bar?
3. Error in the documentation of the "PercentageStyle" property
![image](https://github.com/kavindu-mane/react-percentage-bar/assets/36109878/5a8c4ef5-02af-43cb-9ed0-1e88744bd6a2)

**Comment by kavindu-mane** [comment]
1. I will fix it asap.
2. Linear progress bar can use gradient colors (see demo : https://www.kavindu.me/projects/react-percentage-bar) 
3. What is the error ?

**Comment by saschati** [comment]
1. ty
2. I was talking in the context of the CircularProgressBar 
3. An error was made in the documentation. `[P]ercentageStyle` to `[p]ercentageStyle`, 
without typescript, it was difficult to understand why the props did not work)

**Comment by kavindu-mane** [comment]
issue fixed in new version.
